export const UPDATE_ADD_BTN_WIDTH = "UPDATE_ADD_BTN_WIDTH";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const SET_PRODUCT_INPUT = "SET_PRODUCT_INPUT";
export const SET_STORE_INPUT = "SET_STORE_INPUT";
export const SET_DEFAULT_VALUES = "SET_DEFAULT_VALUES";
